core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('create-subscription', views.createSubscription, name='create-subscription'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('create-customer-stripe-session/', views.createcustomersession, name='session'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('webhooks/', views.webhook_view),

]

ecommerce_subscription/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('core.urls')),
]

users/urls.py
from django.urls import path
from .views import SignupView, LoginView,ProfileView, ProfileUpdate, ShippingUpdateView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<pk>',ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<pk>/profile-update/',ProfileUpdate.as_view(), name='profile-update'),
    path('profile/<pk>/shipping-update/',ShippingUpdateView.as_view(), name='shipping-update'),

]

core/models.py
from django.db import models
from django.conf import settings
from localflavor.us.models import USStateField,USZipCodeField
# Create your models here.
class ShippingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE, related_name='address')
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100)
    state = USStateField()
    zip = USZipCodeField()

    def __str__(self):
        return self.street_address

    class Meta:
        verbose_name_plural = 'Shipping Addresses'

class Subscription(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="subscriptions")
    active = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(ShippingAddress, null=True, on_delete=models.SET_NULL)
    stripe_subscription = models.CharField(max_length=100,blank=True,
        help_text = "The user's Stripe Customer object, if it exists")
    last4 = models.CharField(max_length=4,blank=True,
        help_text = "The user's last 4 credit card digits, if they exist")

    def __str__(self):
        return str(self.user)

core/forms.py
from django import forms
from .models import ShippingAddress
from localflavor.us.forms import USStateField, USZipCodeField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, Row, Column


class AddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = [
            'street_address',
            'apartment_address',
            'city',
            'state',
            'zip',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
            'Shipping',
            'street_address',
            'apartment_address',
            Row(
                Column('city', css_class='form-group col-md-6 mb-0'),
                Column('state', css_class='form-group col-md-4 mb-0'),
                Column('zip', css_class='form-group col-md-2 mb-0'),
                css_class='form-row'
                ),
            ),
        )
        self.fields['apartment_address'].required = False
        self.helper.form_id = 'shippinng-form'
        self.helper.form_method = 'POST'
        self.helper.disable_csrf = True
        self.helper.form_tag = False

core/views.py
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from django.views.generic import View
from django.views.generic.base import TemplateView
from .models import Subscription
from .forms import AddressForm

import json
import stripe

stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

# Create your views here.
class IndexView(TemplateView):
    template_name = 'core/index.html'

class ShippingView(LoginRequiredMixin, View):

    def get(self, *args,**kwargs):
        form = AddressForm()

        context= {
            'form':form,
        }
        return render(self.request, 'core/shipping.html', context)

    def post(self, *args, **kwargs):
        form = AddressForm(self.request.POST)


        if form.is_valid():
            # save address in address model
            new_address = form.save(commit=False)
            new_address.user = self.request.user
            new_address.save()

            # update subscription model with address
            dj_subscription = Subscription.objects.get(user=self.request.user)
            dj_subscription.shipping_address=new_address
            dj_subscription.save()

        return HttpResponseRedirect(reverse('core:checkout'))

class CheckoutView(LoginRequiredMixin,View):
    def get(self, *args,**kwargs):
        return render(self.request, 'core/subscribe.html')

class SuccessView(LoginRequiredMixin,View):
    def get(self, *args,**kwargs):
        return render(self.request, 'core/success.html')


@csrf_exempt
@login_required
def createSubscription(request):
    if request.method=="POST":
        data = json.loads(request.body)
        try:
            # Attach the payment method to the customer
            stripe.PaymentMethod.attach(
                data['paymentMethodId'],
                customer=request.user.stripe_customer,
            )
            # Set the default payment method on the customer
            stripe.Customer.modify(
                request.user.stripe_customer,
                invoice_settings={
                    'default_payment_method': data['paymentMethodId'],
                },
            )

            # Create the subscription
            subscription = stripe.Subscription.create(
                customer=request.user.stripe_customer,
                items=[
                    {
                        'price': data['priceId']
                    }
                ],
                expand=['latest_invoice.payment_intent'],
            )

            # Update the local subscription models
            dj_subscription = Subscription.objects.get(user=request.user)
            try:
                dj_subscription.stripe_subscription = subscription.id
                dj_subscription.active = True
                dj_subscription.last4 = data['last4']
                dj_subscription.save()

            except ObjectDoesNotExist:
                print("could not find user object")

            return JsonResponse(subscription)
        except Exception as e:
            print(str(e))
            return JsonResponse({'message': str(e)}, status=200)

@login_required
def createcustomersession(request):
    user = stripe.Customer.retrieve(request.user.stripe_customer)
    stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

    session = stripe.billing_portal.Session.create(
      customer=user.id,
      return_url= 'http://127.0.0.1:8000/',

    )
    return HttpResponseRedirect(session.url)

@require_POST
@csrf_exempt
def webhook_view(request):
    payload=request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(payload,sig_header, settings.STRIPE_SIGNING_SECRET)
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    if event['type']=='customer.subscription.deleted':
        stripe_sub = event['data']['object']
        sub = Subscription.objects.get(stripe_subscription=stripe_sub['id'])
        sub.active = False
        sub.save()
        print('Subscription Inactive')

    else:
        pass
    return HttpResponse(status=200)

templates/core/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <!--Main layout-->
    <main>
      <div class="container">
        <div class="jumbotron">
          <h1>The Simple Product Subscription</h1>
          <p class="lead">Sometimes simple is better, and less is more.</p>
          <hr class="my-4">
          <p>Subscribe for only $5.00 per month</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'users:signup' %}" role="button">Subscribe</a>
          </p>

        </div>



        <!--Section: Cards-->
        <section class="pt-5">

          <!-- Heading & Description -->
          <div class="wow fadeIn">
            <h2 class="h1 text-center mb-5">What is The Product Subscription?</h2>
            <p class="text-center">The Product Subscription is a simple example
              of a monthly, single-option product subscription.</p>
            <p class="text-center mb-5 pb-5">Subscribe below to create a user
              profile, collect shipping address, and payment information. This
              application also includes webhooks and access to Stripe Billing portal.</p>
          </div>
          <!-- Heading & Description -->

          <hr class="mb-5">
          <!--Grid row-->
          <div class="row mt-3 mx-auto wow fadeIn">
          <!--Grid column-->
            <div class="col-lg-5 col-xl-4 mb-4">
              <div class="view overlay rounded z-depth-1">
                <img src="{% static "img/sample_product.png" %}" alt="Test Product Image" class="img-fluid">
              </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-7 col-xl-7 ml-xl-4 mb-4">
              <h3 class="mb-3 ">
                <strong>The Product Subscription</strong>
              </h3>
              <ul class="grey-text">
                <li>$5.00 per month</li>
                <li>Free Shipping</li>
                <li>Cancel Anytime</li>
              </ul>
              <a href="{% url 'users:signup' %}" class="btn btn-primary btn-lg">Subscribe</a>
            </div>
            <!--Grid column-->
          <!--Grid row-->
        </div>
        </section>
        <!--Section: Cards-->

      </div>
    </main>
    <!--Main layout-->
{% endblock content %}

templates/core/shipping.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

  <div class="container text-center">
    <h1>Subscribe</h1>
    <p class="text-muted "> Step 2 of 3 </p>
    <p class="text-muted ">Enter shipping details. All shipping is free</p>
  </div>

    <div class="col-md-8 my-3 mx-auto">
    	<div class="card mx-5">
    		<div class="card-body">
    					<form  method="POST">
    				    {% csrf_token %}
                  {% crispy form %}
                  <button type="submit" name="button" class="btn btn-primary" id="submit">Next</button>
              </form>
        </div>
    	</div>


{% endblock %}

templates/core/subscribe.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
  <script src="https://js.stripe.com/v3/"></script>
  <link rel="stylesheet" href="{% static "css/StripeElements.css" %}">
{% endblock extra_head %}

{% block content %}
<div class="container text-center">
  <h1>Subscribe!</h1>
  <p class="text-muted "> Step 3 of 3: Enter payment details.</p>
  <p class="text-muted"><strong>Total: $5.00 per Month.</strong></p>
</div>

  <div class="col-md-8 my-3 mx-auto">
    <div class="card mx-5">
      <div class="card-body">
        <form id="subscription-form">
          <p class='hidden' id='priceId'>price_1HtL0GLPfeVqJ0LGqA9O1SN4</p>
          <div class="form-group">
            <label for="name">Full Name</label>
            <input type="text" class="form-control" id='name' placeholder="Name on Card">
          </div>
          <label for="card-element">Payment</label>
          <div id="card-element">
            <!-- Elements will create input elements here -->
          </div>
          <!-- We'll put the error messages in this element -->
          <div id="card-element-errors" role="alert"></div>

          <button id='submit' type="submit">Subscribe</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

{% block extra_scripts %}
  <script src="{% static "js/script.js" %}"></script>
{% endblock extra_scripts %}

templates/core/success.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Congratulations, your subscription is active!</h1>
    <p>Check out your account details under profile,</p>
  </div>
{% endblock content %}