core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('create-subscription', views.createSubscription, name='create-subscription'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('create-customer-stripe-session/', views.createcustomersession, name='session'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('webhooks/', views.webhook_view),

]

ecommerce_subscription/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('core.urls')),
]

users/urls.py
from django.urls import path
from .views import SignupView, LoginView,ProfileView, ProfileUpdate, ShippingUpdateView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<pk>',ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<pk>/profile-update/',ProfileUpdate.as_view(), name='profile-update'),
    path('profile/<pk>/shipping-update/',ShippingUpdateView.as_view(), name='shipping-update'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Product Subscription</title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra_head %}

    {% endblock extra_head %}
</head>

<body>

    <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        <nav class="navbar navbar-nav navbar-expand-lg navbar-light white scrolling-navbar">
            <div class="container">
              <!-- Collapse -->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                  aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item">
                        <h4>The Product Subscription</h4>
                      </li>
                    </ul>
                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">
                          {% if user.is_authenticated %}
                            <li class="nav-item">
                              <a href="{% url 'users:profile' pk=user.pk %}" class="nav-link waves-effect">Profile</a>
                            </li>
                            <li class="nav-item">
                              <a href="{% url 'users:logout' %}" class="nav-link waves-effect">Logout</a>
                            </li>
                          {% else %}
                          <li class="nav-item">
                            <a href="{% url 'users:login' %}" class="nav-link border border-light rounded waves-effect">Login</a>
                          </li>
                          {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->
    <main class="mb-5 py-5">
      <div class="container">
        {% block content %}

        {% endblock %}
      </div>
    </main>
    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_scripts %}

    {% endblock extra_scripts%}
</body>

</html>

templates/user_base.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="mb-5 mt-2 pb-5">

        <div class="col-md-7 mx-auto">

          {% block user_content %}

          {% endblock user_content %}

        </div>

    </div>
{% endblock content %}