core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('create-subscription', views.createSubscription, name='create-subscription'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('create-customer-stripe-session/', views.createcustomersession, name='session'),
    path('shipping/', views.ShippingView.as_view(), name='shipping'),
    path('webhooks/', views.webhook_view),

]

ecommerce_subscription/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('core.urls')),
]

users/urls.py
from django.urls import path
from .views import SignupView, LoginView,ProfileView, ProfileUpdate, ShippingUpdateView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<pk>',ProfileView.as_view(), name='profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<pk>/profile-update/',ProfileUpdate.as_view(), name='profile-update'),
    path('profile/<pk>/shipping-update/',ShippingUpdateView.as_view(), name='shipping-update'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _




# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    stripe_customer = models.CharField(max_length=100,blank=True,
        help_text = "The user's Stripe Customer object, if it exists")


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # removes email from REQUIRED_FIELDS

    objects = UserManager()

    def __str__(self):
        return (self.email)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Row, Column
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
            'Account Information',
            Row(
                Column('first_name', css_class='form-group col-md-6'),
                Column('last_name', css_class='form-group col-md-6'),
            ),
            'email',
            'password1',
            'password2',
            )
        )
        self.helper.form_tag = False

class LoginForm(AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, View, UpdateView
from django.shortcuts import get_object_or_404, render
from django.core.exceptions import ObjectDoesNotExist

from core.models import Subscription, ShippingAddress
from core.forms import AddressForm
from .forms import SignUpForm, LoginForm

import stripe
# Create your views here.

class SignupView(CreateView):
    form_class = SignUpForm
    template_name = 'users/signup.html'

    def get_success_url(self):
        return reverse_lazy('core:shipping')

    def form_valid(self, form):
        stripe.api_key=settings.STRIPE_TEST_SECRET_KEY
        valid = super(SignupView, self).form_valid(form)
        email, password = form.cleaned_data.get('email'), form.cleaned_data.get('password1')
        user = authenticate(email=email,
                            password=password)
        login(self.request, user)

        new_stripe_cust = stripe.Customer.create(
            email=email,
            name=form.cleaned_data.get('first_name') + " " + form.cleaned_data.get('last_name')
        )
        Subscription.objects.create(
            user=self.request.user,
            )
        self.request.user.stripe_customer = new_stripe_cust.id
        self.request.user.save()


        return valid

class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.request.user.pk})

class ProfileView(View, LoginRequiredMixin):

    def get(self, *args, **kwargs):
        user = self.request.user

        try:
            subscription = Subscription.objects.get(user=self.request.user)
            address = subscription.shipping_address

            context = {
                'user':user,
                'last4': subscription.last4,
                'address_pk': address.pk,
                'street_address':address.street_address,
                'apt_address':address.apartment_address,
                'city':address.city,
                'state':address.state,
                'zip':address.zip,
                'active':subscription.active,
                'subscription':subscription.pk,
            }
        except ObjectDoesNotExist:
            context = {
                'user':user,
                'subscription':''
            }

        return render(self.request, 'users/profile.html', context)

class ProfileUpdate(UpdateView):
    model = get_user_model()
    template_name = 'users/profile_update.html'
    fields = ['first_name', 'last_name', 'email',]

    def get_success_url(self):
        pk = self.object.pk
        return reverse_lazy('users:profile',args=[pk])

class ShippingUpdateView(LoginRequiredMixin, UpdateView):
    model=ShippingAddress
    form_class = AddressForm
    template_name = 'users/shipping_update.html'


    def get_success_url(self):
        pk = self.object.pk
        return reverse_lazy('users:profile',args=[pk])

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main >

  <div class="container">
    <div class="jumbotron wow fadeIn">
      <h1 class="">Login</h1>

    </div>
      <div class="col-md-8 mx-auto">
        <form method="POST">
          {% csrf_token %}
          {% crispy form %}
          <input type="submit" class="btn btn-primary" value="Login">
        </form>
      </div>


  </div>
</main>







{% endblock content %}

templates/users/profile.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <h1>Hello, {{user.first_name}}</h1>
</div>

<div class="col-md-7 mx-auto">
  <div class="card">
    <div class="card-header">
      <h5 class="card-title">Account Info</h5>
    </div>

    <div class="card-body  mb-2">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <p class="card-text">Name:<span class="float-right">
            {{user.first_name}} {{user.last_name}}</span></p>
          <p class="card-text">Email:<span class="float-right">{{user.email}}</span></p>
          <a href="{% url 'users:profile-update' pk=user.pk %}"class='btn btn-outline-secondary float-right'>Update</a>

        </li>

          {% if subscription %}
          {% if address_pk %}

            <li class="list-group-item">
              <p class="card-text"><strong>Shipping Address:</strong>
                  <span class="float-right">{{street_address}}{% if apt_address %}, {{apt_address}}{% endif %} <br>
                    {{city}}, {{state}} {{zip}}</span></p>
              <br>
              <a href="{% url 'users:shipping-update' pk=address_pk %}"class='btn btn-outline-secondary float-right'>Update</a>
              <br>
            </li>

          {% endif %}
          <br>

          <li class="list-group-item">
            {% if last4 %}

              <p class="card-text"><strong>Payment:</strong>
                <span class="float-right">**** **** **** {{last4}}</span>
              </p>
            {% endif %}

            <br>

            <form method="POST" action="{% url 'core:session' %}">
              {% csrf_token %}
                <button class="btn btn-success float-right" type="submit">Manage Billing</button>
            </form>

            {% if active %}
            <p><strong>Your subscription is active!</strong></p>
            {% else %}
            <p><strong>Your subscription is inactive</strong></p>
            {% endif %}

            <br>
        </li>

        {% else %}
          <br>
          <p> <strong>You don't have a subscription yet!</strong> </p>

        {% endif %}

      </ul>
    </div>
  </div>
</div>

{% endblock content %}

templates/users/profile_update.html
{% extends "user_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block user_content %}
  <div class="card">
    <div class="card-header">
      Account Info Update
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" name="button" class="btn btn-success" id="submit">Submit</button>
      </form>

    </div>
  </div>

{% endblock %}

templates/users/shipping_update.html
{% extends "user_base.html" %}
{% load crispy_forms_tags %}

{% block user_content %}
  <div class="card">
    <div class="card-header">
      Shipping Address Update
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" name="button" class="btn btn-success" id="submit">Submit</button>
      </form>

    </div>
  </div>

{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container text-center">
  <h1>Subscribe!</h1>
  <p class="text-muted "> Step 1 of 2: Enter account details.</p>
</div>

  <div class="col-md-8 my-3 mx-auto">
    <div class="card mx-5">
      <div class="card-body">
            <form method="POST">
              {% csrf_token %}
                {% crispy form %}
                <button type="submit" class="btn btn-primary">Next</button>
            </form>
      </div>
    </div>
  </div>




{% endblock %}